version: "3"

services:
    nats-server:
        image: nats:latest

    client-gateway:
        build:
            context: ./client-gateway
            dockerfile: Dockerfile.prod
        image: client-gateway
        ports:
            - ${CLIENT_GATEWAY_PORT}:${CLIENT_GATEWAY_PORT}
        environment:
            - PORT=${CLIENT_GATEWAY_PORT}
            - NATS_SERVERS=nats://nats-server:4222
    auth-ms:
        build:
            context: ./auth-ms
            dockerfile: Dockerfile.prod
        image: auth-ms
        environment:
            - PORT=3000
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=${AUTH_MS_DATABASE_URL}
            - JWT_SECRET=${JWT_SECRET}

    products-ms:
        build:
            context: ./products-ms
            dockerfile: Dockerfile.prod
        image: products-ms
        environment:
            - PORT=3000
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=file:./dev.db

    orders-ms:
        build:
            context: ./orders-ms
            dockerfile: Dockerfile.prod
            args:
                - ORDERS_MS_DATABASE_URL=${ORDERS_MS_DATABASE_URL}
        image: orders-ms
        environment:
            - PORT=3000
            - DATABASE_URL=${ORDERS_MS_DATABASE_URL}
            - NATS_SERVERS=nats://nats-server:4222

    payments-ms:
        build:
            context: ./payments-ms
            dockerfile: Dockerfile.prod
        image: payments-ms
        environment:
            - PORT=3000
            - NATS_SERVERS=nats://nats-server:4222
            - STRIPE_SECRET=${PAYMENT_MS_STRIPE_SECRET}
            - STRIPE_SUCCESS_URL=${PAYMENT_MS_STRIPE_SUCCESS_URL}
            - STRIPE_CANCEL_URL=${PAYMENT_MS_STRIPE_CANCEL_URL}
            - STRIPE_ENDPOINT_SECRET=${PAYMENT_MS_STRIPE_ENDPOINT_SECRET}
