version: "3"

services:
    nats-server:
        image: nats:latest
        ports:
            - 8222:8222

    client-gateway:
        build: ./client-gateway
        ports:
            - ${CLIENT_GATEWAY_PORT}:3000
        volumes:
            - ./client-gateway/src:/usr/src/app/src
        command: yarn start:dev
        environment:
            - PORT=3000
            - NATS_SERVERS=nats://nats-server:4222

    auth-ms:
        # depends_on:
        #     - mongo-db
        build: ./auth-ms
        volumes:
            - ./auth-ms/src:/usr/src/app/src
        command: yarn start:dev
        environment:
            - PORT=3004
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=mongodb+srv://root:lmB8qfZymlPXlxVN@cluster0.33www2j.mongodb.net/auth?retryWrites=true&w=majority&appName=Cluster0
            - JWT_SECRET=${JWT_SECRET}
    # mongo-db:
    #     image: mongo:latest
    #     restart: always
    #     volumes:
    #         - ./auth-ms/mongodb-data:/data/db
    #     ports:
    #         - 27017:27017
    #     environment:
    #         - MONGO_INITDB_ROOT_USERNAME=root
    #         - MONGO_INITDB_ROOT_PASSWORD=123456

    products-ms:
        build: ./products-ms
        volumes:
            - ./products-ms/src:/usr/src/app/src
        command: yarn start:dev
        environment:
            - PORT=3001
            - NATS_SERVERS=nats://nats-server:4222
            - DATABASE_URL=file:./dev.db

    orders-ms:
        depends_on:
            - orders-db
        build: ./orders-ms
        volumes:
            - ./orders-ms/src:/usr/src/app/src
        command: yarn start:dev
        environment:
            - PORT=3002
            - DATABASE_URL=postgresql://postgres:123456@orders-db:5432/postgres?schema=public
            - NATS_SERVERS=nats://nats-server:4222

    orders-db:
        container_name: orders_database
        image: postgres:16.2
        restart: always
        volumes:
            - ./orders-ms/postgres:/var/lib/postgresql/data
        ports:
            - 5432:5432
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
            - POSTGRES_DB=ordersdb

    payments-ms:
        build: ./payments-ms
        ports:
            - 3003:3003
        volumes:
            - ./payments-ms/src:/usr/src/app/src
        command: yarn start:dev
        environment:
            - PORT=3003
            - NATS_SERVERS=nats://nats-server:4222
            - STRIPE_SECRET=${PAYMENT_MS_STRIPE_SECRET}
            - STRIPE_SUCCESS_URL=${PAYMENT_MS_STRIPE_SUCCESS_URL}
            - STRIPE_CANCEL_URL=${PAYMENT_MS_STRIPE_CANCEL_URL}
            - STRIPE_ENDPOINT_SECRET=${PAYMENT_MS_STRIPE_ENDPOINT_SECRET}
